### ISSUE TITLE
Version of V2 Patient Identity feed

### ISSUE THREAD

**Issue by iheos** [usnistgov/iheos-toolkit2#260]
I was wondering if it is possible to somehow change the HL7v2 Patient Feed that is send to the registry to version 2.3.1 instead of the current 2.3 message.

Since TF vol2a states HL7v2.3.1 was selected for this transaction I would expect the Patient Feed v2 in XDSTools to be in this version 2.3.1.

**Comment by Thopap** [comment]
I had the same issue. Any way to reconfigure the XDS tools to use HL7 version 2.3.1?

**Comment by Thopap** [comment]
Any chance to fix this issue before the next connectathon?

**Comment by iheos** [comment]
Fixed on develop and master branches.  Fix will show up in next release
(bug fix or otherwise).

**Comment by Thopap** [comment]
The version 2.3.1 is fine now, but the message is still not compliant to ITI-8:
https://gazelle.ihe.net/EVSClient/hl7v2Result.seam?&oid=1.3.6.1.4.1.12559.11.1.2.1.4.844627

The nametypecode is missing in the message. Should I create another issue for that or could you fix this with this one?

**Comment by iheos** [comment]
I've updated PID-5 to be

APPLESEED^JOHN^A^^^^L

in the v6 sources.  It will go out in the next v6 release.
